name: pagination_core
description: A simple and reusable pagination handler for any state management solution in Flutter.
version: 1.0.5
homepage: https://github.com/Sonia-dev/pagination_core

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pagination_example.png


funding:
  - https://www.buymeacoffee.com/sonia_flutter

